/**
 * The HTML body of a wali notification.
 *
 * apify/send-mail appends its own attribution line to whatever HTML it is given
 * ("<br><br>This is an email generated by the Send Email Actor..."). Since that
 * lands inside our markup, the template deliberately ends with an open, small,
 * grey container so the attribution renders as a footnote rather than as raw
 * text after the design. It is not hidden, only styled.
 */
export function waliEmailHtml(opts: {
  waliName: string;
  wardName: string;
  suitorName?: string;
}) {
  const { waliName, wardName, suitorName } = opts;
  const first = wardName.split(' ')[0];
  const who = suitorName ?? 'Someone';

  return `
<div style="margin:0;padding:24px 0;background:#12352A;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;">
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr><td align="center">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="520" style="width:520px;max-width:92%;">

        <tr><td style="padding:0 0 22px 0;">
          <span style="font-size:22px;font-weight:700;color:#F1FBE2;letter-spacing:0.5px;">Khitbah</span>
        </td></tr>

        <tr><td style="background:#1B4A38;border:1px solid rgba(255,255,255,0.14);border-radius:18px;padding:30px;">
          <p style="margin:0 0 6px 0;font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#F4CE5E;font-weight:700;">
            A request is waiting
          </p>
          <p style="margin:0 0 20px 0;font-size:23px;line-height:31px;color:#F1FBE2;font-weight:700;">
            Assalamu alaikum ${waliName}
          </p>
          <p style="margin:0 0 16px 0;font-size:15px;line-height:24px;color:#B6E6BE;">
            ${who} has sent a request for <strong style="color:#F1FBE2;">${wardName}</strong>.
            It is waiting for your review.
          </p>
          <p style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#B6E6BE;">
            Nothing reaches ${first} until you approve it. If you approve, the request passes to her
            and the decision is hers alone.
          </p>
          <table role="presentation" cellpadding="0" cellspacing="0" border="0">
            <tr><td style="background:#7DE6A3;border-radius:999px;">
              <span style="display:inline-block;padding:13px 26px;font-size:15px;font-weight:700;color:#14301F;">
                Open Khitbah to review
              </span>
            </td></tr>
          </table>
        </td></tr>

        <tr><td style="padding:20px 4px 0 4px;">
          <p style="margin:0;font-size:12px;line-height:19px;color:#8FC79C;">
            You are receiving this because ${first} listed you as her wali on Khitbah.
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
  <div style="max-width:520px;margin:14px auto 0 auto;font-size:10px;line-height:15px;color:#4d7a5f;text-align:center;">`;
  // Intentionally left open: the mail service's attribution is appended here.
}

export function waliEmailText(opts: { waliName: string; wardName: string; suitorName?: string }) {
  const { waliName, wardName, suitorName } = opts;
  const first = wardName.split(' ')[0];
  const who = suitorName ? `${suitorName} has` : 'Someone has';
  return (
    `Assalamu alaikum ${waliName},\n\n` +
    `${who} sent a request for ${wardName} on Khitbah. It is waiting for your review.\n\n` +
    `Nothing reaches ${first} until you approve it. If you approve, the request passes to her ` +
    `and the decision is hers alone.\n\n` +
    `You are receiving this because ${first} listed you as her wali on Khitbah.`
  );
}
